version: '3.5'

services:

    postgres:
        container_name: postgres_container
        image: postgres:latest
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            PGDATA: /data/postgres
        network_mode: 'host'
        volumes:
            - ./data/postgres:/data/postgres
        ports:
            - 5432:5432
        restart: unless-stopped

    zookeeper:
        image: bitnami/zookeeper:latest
        network_mode: 'host'
        ports:
            - 2181:2181
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes

    kafka:
        image: bitnami/kafka:latest
        ports:
            - 9092:9092
        network_mode: 'host'
        environment:
            - KAFKA_BROKER_ID=1
            - KAFKA_LISTENERS=PLAINTEXT://:9092
            - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
            - ALLOW_PLAINTEXT_LISTENER=yes
            - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
        depends_on:
            - zookeeper

    torcedores-app:
        image: torcedor-app:1.0.7
        container_name: torcedores-app
        network_mode: 'host'
        expose:
            - 8084
            - 8080
        ports:
            - 8084:8084
        restart: unless-stopped
        depends_on:
            - postgres
            - kafka

    torcedores-front:
        image: torcedores-site:1.0.0
        network_mode: 'host'
        expose:
            - 4200
        ports:
            - 4200:4200
        depends_on:
            - torcedores-app
