version: '3.5'

services:
    postgres:
        container_name: postgres_container
        image: postgres:latest
        network_mode: bridge
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postygres
            PGDATA: /data/postgres
        volumes:
            - ./data/postgres:/data/postgres
        ports:
            - "5432:5432"
        restart: unless-stopped

    zookeeper:
        image: 'bitnami/zookeeper:latest'
        ports:
            - '2181:2181'
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes

    kafka:
        image: 'bitnami/kafka:latest'
        ports:
            - '9092:9092'
        environment:
            - KAFKA_BROKER_ID=1
            - KAFKA_LISTENERS=PLAINTEXT://:9092
            - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
            - ALLOW_PLAINTEXT_LISTENER=yes
        depends_on:
            - zookeeper

    torcedores-app:
        image: torcedore-app:1.0.1
        network_mode: bridge
        container_name: torcedores-app
        expose:
            - 8080
        ports:
            - 8080:8080
        restart: unless-stopped
        depends_on:
            - postgres
            - kafka
        links:
            - postgres

