version: '3.5'

services:
    postgres:
        container_name: postgres_container
        image: postgres:latest
        network_mode: bridge
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postygres
            PGDATA: /data/postgres
        volumes:
            - ./data:/data/postgres
        ports:
            - "5432:5432"
        restart: unless-stopped

    torcedores-app:
        image: torcedore-app:1.0.0
        network_mode: bridge
        container_name: torcedores-app
        expose:
            - 8080
        ports:
            - 8080:8080
        restart: unless-stopped
        depends_on:
            - postgres
        links:
            - postgres

